security:
    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
               class: AppBundle:User
               property: username


    role_hierarchy:
        ROLE_VISITOR:     ROLE_USER
        ROLE_PROVIDER:    [ROLE_USER, ROLE_VISITOR]
        ROLE_ADMIN:       [ROLE_USER, ROLE_PROVIDER, ROLE_VISITOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

        secured_area:

            logout:
                path:   /logout
                target: /
                invalidate_session: false
                delete_cookies:
                    a: { path: null, domain: null }
                    b: { path: null, domain: null }



            form_login:
                csrf_token_generator: security.csrf.token_manager


    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\User: bcrypt

    access_control:
         - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
         - { path: ^/admin, roles: ROLE_ADMIN }

